### ISSUE TITLE
b1.7.3 (Poseidon v1.1.10) - Taterlib b1.7.3 v1.1.0 fails to load

### ISSUE THREAD

**Issue by bobatealee** [p0t4t0sandwich/TaterLib#133]
### Debug Information

21:45:28 [SEVERE] Could not load 'plugins\taterlib-b1.7.3-1.1.0.jar' in folder 'plugins':
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:72)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:194)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:231)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:153)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:126)
        at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:93)
        at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigurationManager.java:43)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:160)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:392)
        at net.minecraft.server.ThreadServerApplication.run(ThreadServerApplication.java:13)
Caused by: java.lang.NullPointerException: Cannot invoke "java.io.File.getParentFile()" because the return value of "org.bukkit.plugin.java.JavaPlugin.getDataFolder()" is null
        at dev.neuralnexus.taterlib.lib.bstats.bukkit.Metrics.<init>(Metrics.java:35)
        at dev.neuralnexus.taterlib.bstats.bukkit.BukkitMetricsAdapter.setupMetrics(BukkitMetricsAdapter.java:15)
        at dev.neuralnexus.taterlib.bstats.MetricsAdapter.setupMetrics(MetricsAdapter.java:32)
        at dev.neuralnexus.taterlib.TaterLib.start(TaterLib.java:120)
        at dev.neuralnexus.taterlib.TaterLibPlugin.pluginStart(TaterLibPlugin.java:31)
        at dev.neuralnexus.taterlib.bukkit.BukkitTaterLibPlugin.platformInit(BukkitTaterLibPlugin.java:38)
        at dev.neuralnexus.taterlib.plugin.Loader.lambda$onInit$2(Loader.java:46)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at dev.neuralnexus.taterlib.plugin.Loader.onInit(Loader.java:46)
        at dev.neuralnexus.taterlib.loader.platforms.BukkitLoaderPlugin.<init>(BukkitLoaderPlugin.java:24)
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        ... 11 more
21:45:28 [SEVERE] Could not load 'plugins\switchboard-1.0.4-R0.2-SNAPSHOT.jar' in folder 'plugins': TaterLib
org.bukkit.plugin.UnknownDependencyException: TaterLib
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:146)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:231)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:153)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:126)
        at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:93)
        at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigurationManager.java:43)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:160)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:392)
        at net.minecraft.server.ThreadServerApplication.run(ThreadServerApplication.java:13)
21:45:28 [INFO] Couldn't access Thread.inheritableThreadLocals. Reference finalizer threads will inherit thread local values.

### Description of behavior

When booting up my server running Project Poseidon v1.1.10 and Taterlib b1.7.3 v1.1.0, the plugin fails to load.

### Reproduction Steps

```markdown
Steps to reproduce the behavior:
1. Grab Project Poseidon v1.1.10: https://github.com/retromcorg/Project-Poseidon/releases/download/1.1.10-241215-0208-8f2bb13/project-poseidon-1.1.10.jar
2. Grab Taterlib v1.1.0
3. Run the server with both of these
4. Taterlib fails to load
```

**Comment by p0t4t0sandwich** [comment]
The issue has been fixed in dev, just need to finish the TaterLib release and update Switchboard to the new API changes
